import { supabase } from "../lib/supabase";

export type ContextModule = { id: string; user_id: string; name: string; description: string | null; is_enabled: boolean; priority: number; version: number; created_at: string; updated_at: string };
export type ContextItem = { id: string; user_id: string; module_id: string; item_type: string; content: string; is_enabled: boolean; sort_order: number; version: number; created_at: string; updated_at: string };
export type ContextRevision = { id: string; user_id: string; module_id: string | null; item_id: string | null; version: number; change_type: "insert" | "update" | "delete"; snapshot: Record<string, unknown>; created_at: string };

const ensure = (result: { error: { message: string } | null }) => { if (result.error) throw result.error; };

export const ContextRepository = {
  async listContextModules(userId: string) { const { data, error } = await supabase.from("context_modules").select("*").eq("user_id", userId).order("priority", { ascending: false }).order("updated_at", { ascending: false }); ensure({ error }); return (data ?? []) as ContextModule[]; },
  async createContextModule(userId: string, input: Pick<ContextModule, "name"> & Partial<Pick<ContextModule, "description" | "priority" | "is_enabled">>) { const { data, error } = await supabase.from("context_modules").insert({ ...input, user_id: userId }).select().single(); ensure({ error }); return data as ContextModule; },
  async updateContextModule(userId: string, id: string, patch: Partial<Pick<ContextModule, "name" | "description" | "priority" | "is_enabled">>) { const { data, error } = await supabase.from("context_modules").update(patch).eq("id", id).eq("user_id", userId).select().single(); ensure({ error }); return data as ContextModule; },
  async deleteContextModule(userId: string, id: string) { const { error } = await supabase.from("context_modules").delete().eq("id", id).eq("user_id", userId); ensure({ error }); },
  async listContextItems(userId: string, moduleId: string) { const { data, error } = await supabase.from("context_items").select("*").eq("user_id", userId).eq("module_id", moduleId).order("sort_order"); ensure({ error }); return (data ?? []) as ContextItem[]; },
  async createContextItem(userId: string, moduleId: string, input: Pick<ContextItem, "content"> & Partial<Pick<ContextItem, "item_type" | "is_enabled" | "sort_order">>) { const { data, error } = await supabase.from("context_items").insert({ ...input, module_id: moduleId, user_id: userId }).select().single(); ensure({ error }); return data as ContextItem; },
  async updateContextItem(userId: string, id: string, patch: Partial<Pick<ContextItem, "content" | "item_type" | "is_enabled" | "sort_order">>) { const { data, error } = await supabase.from("context_items").update(patch).eq("id", id).eq("user_id", userId).select().single(); ensure({ error }); return data as ContextItem; },
  async deleteContextItem(userId: string, id: string) { const { error } = await supabase.from("context_items").delete().eq("id", id).eq("user_id", userId); ensure({ error }); },
  async reorderContextItems(userId: string, moduleId: string, orderedIds: string[]) { await Promise.all(orderedIds.map((id, index) => this.updateContextItem(userId, id, { sort_order: index }))); return this.listContextItems(userId, moduleId); },
  async listRecentRevisions(userId: string, limit = 20) { const { data, error } = await supabase.from("context_revisions").select("*").eq("user_id", userId).order("created_at", { ascending: false }).limit(limit); ensure({ error }); return (data ?? []) as ContextRevision[]; },
  async getEffectiveUserContext(userId: string, maxLength = 12000) { const modules = await this.listContextModules(userId); const enabled = modules.filter((module) => module.is_enabled); const items = (await Promise.all(enabled.map((module) => this.listContextItems(userId, module.id)))).flat().filter((item) => item.is_enabled).sort((a, b) => a.sort_order - b.sort_order); let remaining = maxLength; return enabled.flatMap((module) => items.filter((item) => item.module_id === module.id).map((item) => ({ moduleId: module.id, moduleName: module.name, version: Math.max(module.version, item.version), itemType: item.item_type, content: item.content }))).filter((entry) => { if (remaining <= 0) return false; remaining -= entry.content.length; return true; }); },
};
